### ISSUE TITLE
Podes usar interporlación de strings de groovy "hola ${nombre}"

### ISSUE THREAD

**Issue by maurociancio** [tomasmacia/PasaLaBocha#8]
https://github.com/tomasmacia/PasaLaBocha/blob/783d944389bc35c60297e4a4bb2138543700b6d4/grails-app/taglib/pasalabocha/CanchaTagLib.groovy#L20

**Comment by FrancoLiberali** [comment]
Este código era viejo y ya no era utilizado por lo que fue eliminado en cc1dcb6
